version: "3"
services:
  sdc:
    image: graphpathai/datacollector:3.4.2
    ports:
      - "18630:18630"
    volumes:
      - "./streamsets/datasets:/home/sdc/data"
      - "./streamsets/data:/data"
